language: c
dist: trusty
os: linux
sudo: required

git:
  depth: 5


before_install:
  - wget -c http://www.codesourcery.com/sgpp/lite/arm/portal/package4571/public/arm-none-linux-gnueabi/arm-2009q1-203-arm-none-linux-gnueabi-i686-pc-linux-gnu.tar.bz2
  - tar xjf arm-2009q1-203-arm-none-linux-gnueabi-i686-pc-linux-gnu.tar.bz2
  - export PATH="$PWD/arm-2009q1/bin:$PATH"
  - sudo apt-get install -y libc6-i386


script:
  - cd API
  - make CROSS_COMPILE=arm-none-linux-gnueabi- CFLAGS="-Wall -Wextra -Wno-unused-parameter -Wno-pointer-sign"
