language: c
dist: trusty

git:
  depth: 5

matrix:
  include:
    - os: linux
      sudo: required
    - os: osx

before_install:
  - wget -c http://www.codesourcery.com/sgpp/lite/arm/portal/package4571/public/arm-none-linux-gnueabi/arm-2009q1-203-arm-none-linux-gnueabi-i686-pc-linux-gnu.tar.bz2
  - tar xvjf arm-2009q1-203-arm-none-linux-gnueabi-i686-pc-linux-gnu.tar.bz2
  - export PATH="$PWD/arm-2009q1/arm-none-linux-gnueabi/bin/"
  - "$CC --version"

script:
  - cd API
  - make PREFIX=arm-none-linux-gnueabi-
